[versions]
mcSafeResources = "0.0.2"
gradlePluginPublish = "2.0.0"
gson = "2.13.2"
kotlin = "2.2.21"
jetbrainsAnnotations = "26.0.2-1"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }

[plugins]
gradlePluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mcSafeResources = { id = "dev.echoellet.mc-safe-resources", version.ref = "mcSafeResources" }
