[versions]
minecraftSafeResources = "0.0.1"
gradlePluginPublish = "2.0.0"
gson = "2.13.2"
kotlin = "2.2.21"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
gradlePluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
minecraftSafeResources = { id = "dev.echoellet.minecraft-safe-resources", version.ref = "minecraftSafeResources" }
